spring.application.name=com

spring.datasource.url=jdbc:postgresql://localhost:5432/moviePoster_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.redis.host=localhost
spring.redis.port=6379

# ????????? SMS API Messaggio
messaggio.api.url=https://api.messaggio.com/v1/sms/send
messaggio.api.token=???_API_TOKEN
messaggio.sender=MyApp

# ????????????? ???????? 3 ???? ???? ?????? ??????????
spring.kafka.producer.retries=3
spring.kafka.producer.retry.backoff.ms=1000

spring.ai.google.genai.api-key=AIzaSyDeTuPOWC80MciTRtf704kSh8h77017Adk
spring.ai.google.genai.chat.options.model=gemini-2.0-flash




